import { mkdir, writeFile } from "node:fs/promises";
import type { Context } from "../run.js";
import { resolvePathItems } from "../utils/openapi.js";

export async function resolveTypesAndWrite(context: Context) {
	const pathItems = resolvePathItems(context.specifications);
	const paths = pathItems.map((it) => `${it.path} ${it.method}`);

	await mkdir(`./.cache/open-api-code-gen`, { recursive: true });
	await writeFile(
		`./.cache/open-api-code-gen/${context.name}.d.ts`,
		`// Generated by @lightbase/open-api-code-gen
import type { GeneratorHooks } from "@lightbase/open-api-code-gen";

declare module "@lightbase/open-api-code-gen" {
  interface GeneratorPathImplementation {
    ${context.name}: {
${paths.map((it) => `      "${it}"?: GeneratorHooks`).join(";\n")}
    }
  }
}
`,
	);
}
