name: "Build, Lint, Test"

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: |
    ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-lint-test:
    uses: lightbasenl/platforms/.github/workflows/lib-ci.yml@main
    strategy:
      matrix:
        runs:
          - node-version: 20
          - node-version: 22
    with:
      node-version: ${{ matrix.node-version }}
      command: |
        npm run build:ws
        npm run lint:ci:ws
        npm run test

  check-licenses:
    uses: lightbasenl/platforms/.github/workflows/lib-license-checker.yml@main
