name: Build, Lint, Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Can't cache, since we don't commit the lockfile
          node-version: 20

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build:ws

      - name: Lint
        run: |
          npm run lint:ci:ws

      - name: Test
        run: |
          npm run test:ws

  check-licenses:
    uses: lightbasenl/platforms/.github/workflows/lib-license-checker.yml@main
