name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  slash_command_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.REPO_ADMIN_TOKEN }}
          commands: |
            lint
